language: ruby
rvm:
  - 2.1.5

notifications:
  email:
    - mike.korcynski@tufts.edu

before_install:
  - sudo apt-get update
  - sudo apt-get -y install libreoffice
  - gem install bundler -v 1.9.4

before_script:
  - bundle exec rake config:copy db:setup
  - cp config/ldap.yml.sample config/ldap.yml
  - cp config/devise.yml.sample config/devise.yml
script:
  - bundle exec rake ci

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

bundler_args: --without development debug

services:
  - redis-server
