development:
  user: fedoraAdmin
  password: <%= Rails.application.secrets.fedora_password %>
  url: http://127.0.0.1:8983/fedora
test: &TEST  
  user: fedoraAdmin
  password: <%= Rails.application.secrets.fedora_password %>
  url: <%= "http://127.0.0.1:#{ENV['TEST_JETTY_PORT'] || 8983}/fedora-test" %>
